### PR TITLE
Cross-build twinagle-scalapb-plugin for sbt 1.x and sbt 2.x

### PR DESCRIPTION
**Pull request by rbscgh**
## Summary

Cross-builds `twinagle-scalapb-plugin` for **both sbt 1.x and sbt 2.x**, and migrates the scalapb stack as required to make the sbt-2 artifact actually work end-to-end.

The build keeps an **sbt 1.x launcher** and cross-publishes both plugin artifacts via `crossScalaVersions = [2.12, 3]` + `pluginCrossBuild / sbtVersion` (Scala 2.12 → sbt 1.x, Scala 3.8.4 → sbt 2.0.0). This is the pattern used by sbt's own reference plugins (sbt-protoc, sbt-assembly, sbt-buildinfo) per the [sbt 2 plugin cross-building guide](https://www.scala-sbt.org/2.x/docs/en/changes/migrating-from-sbt-1.x.html#cross-building-sbt-plugins).

Produces:
- `twinagle-scalapb-plugin_2.12_1.0` — for sbt 1.x users
- `twinagle-scalapb-plugin_sbt2_3` — for sbt 2.x users

## Key decisions

**1. sbt 1.x launcher, not sbt 2 — even though we target sbt 2.**
The guide's "build *from* sbt 2" path requires `sbt-projectmatrix`, which has **no sbt-2 release** (only `_2.12_1.0` exists). Building from an sbt-1 launcher with `pluginCrossBuild / sbtVersion` is the only way to produce *both* artifacts today, and is exactly what sbt-protoc/sbt-assembly do. "Build with sbt 2" here means the Scala-3 axis *compiles against* sbt 2.0.0 — the `_sbt2_3` artifact runs under sbt 2.0.0 and passes its e2e test.

**2. Split the Scala-3 version: runtime stays LTS, codegen+plugin move to 3.8.4.**
sbt 2.0.0's build DSL runs on Scala 3.8.4, so the plugin (and `codegen`, which it `dependsOn`) must compile on that axis. `twinagle-runtime` — the end-user library — stays on **LTS 3.3.7**. sbt can't cross-build one project at two Scala-3 versions (both produce `_3`), hence the split.

**3. Migrate scalapb to 1.0.0-alpha.5 — the hard blocker.**
`sbt-protoc`'s only sbt-2 variant (`_sbt2_3` 1.1.0-RC1) depends on `protoc-bridge_3` (a native Scala-3 trait). But **every stable scalapb 0.11.x `compilerplugin_3` is compiled against `protoc-bridge_2.13`**, whose `ProtocCodeGenerator.$init$` ABI is absent in `protoc-bridge_3` → `NoSuchMethodError` at code-generation time. Only scalapb **1.0.0-alpha.4+** ships a `compilerplugin_3` that is natively `protoc-bridge_3`. So a working sbt-2 plugin *requires* the alpha line. (The repo already started this in #494.)
- `scalapb-json4s` has only published `1.0.0-alpha.1` (pulls scalapb-runtime alpha.1); its transitive scalapb-runtime is excluded so consumers get a single coherent **alpha.5** (sbt's early-semver check otherwise rejects the alpha.1→alpha.5 eviction). The exclude is per-dependency so it serializes into the published POM/ivy and downstream users inherit it.

**4. Scala 3 / `-Werror` source fixes.**
`-Xfatal-warnings` → `-Werror` on Scala 3 (the alias is itself a fatal deprecation); dropped `private[this]`; dropped the explicit `Seq[Def.Setting[_]]` return type (`_` wildcard is fatal on 3.x, `?` won't compile on 2.12); explicit `InclExclRule` element type where sbt 2 no longer applies the implicit conversion.

**5. e2e scripted test runs on both axes.**
Pinned `scalaVersion := 2.13` (resolves exact-match published artifacts on both sbt axes). Deleted its `project/build.properties` so scripted runs it on **both** axes (sbt treats that file as a per-axis filter). `@unchecked` on partial pattern bindings + dropped now-useless `@nowarn` (2.13 lint differences).

**6. CI: JDK 8 → 17** (sbt 2.0.0 requires 17), and `+test scripted` → `+test +publishLocal +plugin/scripted` — bare `scripted` only exercised the sbt-1 axis, and the 2.13-pinned e2e needs `twinagle-runtime_2.13` published first.

## Test plan

- [x] `sbt +test` — 50 tests pass across Scala 2.12 / 2.13 / 3.3.7
- [x] `sbt +publishLocal` — both `_2.12_1.0` and `_sbt2_3` plugin artifacts publish
- [x] `sbt +plugin/scripted` — `generator/e2e` passes under **sbt 1.11.7** (2.12 axis) **and** **sbt 2.0.0** (3.8.4 axis), 10 examples each
- [x] `sbt scalafmtCheckAll` — clean
- [x] CI green on JDK 17

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

File: build.sbt [hunk 1]
```diff
@@ -11,23 +14,28 @@ lazy val commonSettings = List(
       case Some((2, _)) => scalacOptions ++= Seq("-Xlint")
       case _            => ()
     }
+    // Scala 3 renamed -Xfatal-warnings to -Werror (the old alias is itself deprecated).
+    val fatalWarnings = CrossVersion.partialVersion(scalaVersion.value) match {
+      case Some((2, _)) => "-Xfatal-warnings"
+      case _            => "-Werror"
+    }
```
[the remark this answers is not in the document]
Comment (rbscgh) [reply build.sbt]: 🤖 *Automated response from Claude Code* — Addressed in abdba67. Refactored the `scalacOptions` block to return a single `Seq` per axis, so `-Xlint` is now genuinely applied on Scala 2.12/2.13 (no longer a discarded `Setting`). Verified the 2.x sources are lint-clean under `-Xlint -Xfatal-warnings` via `+test`.

File: plugin/src/sbt-test/generator/e2e/src/test/scala/twitch/twirp/example/haberdasher/HaberdasherSpec.scala [hunk 2]
```diff
@@ -36,7 +36,7 @@ class HaberdasherSpec extends Specification {
       }
 
       "produces TwinagleExceptions for error responses" in {
-        val Throw(ex: TwinagleException) = Await.result(client.makeHat(Size(-1)).liftToTry)
+        val Throw(ex: TwinagleException) = Await.result(client.makeHat(Size(-1)).liftToTry): @unchecked
```
[the remark this answers is not in the document]
Comment (rbscgh) [reply plugin/src/sbt-test/generator/e2e/src/test/scala/twitch/twirp/example/haberdasher/HaberdasherSpec.scala]: 🤖 *Automated response from Claude Code* — Addressed in abdba67. Replaced the refutable `@unchecked` binding with `must throwA[TwinagleException].like { case ex: TwinagleException => ... }` (explicit pattern type so `ex.code` resolves). Verified passing on both the sbt 1.x and sbt 2.x scripted axes.

File: plugin/src/sbt-test/generator/e2e/src/test/scala/twitch/twirp/example/haberdasher/HaberdasherSpec.scala [hunk 3]
```diff
@@ -59,7 +59,7 @@ class HaberdasherSpec extends Specification {
...
```
[the remark this answers is not in the document]
Comment (rbscgh) [reply plugin/src/sbt-test/generator/e2e/src/test/scala/twitch/twirp/example/haberdasher/HaberdasherSpec.scala]: 🤖 *Automated response from Claude Code* — Addressed in abdba67. Replaced the refutable `@unchecked` binding with `must throwA[TwinagleException].like { case ex: TwinagleException => ... }` (explicit pattern type so `ex.code` resolves). Verified passing on both the sbt 1.x and sbt 2.x scripted axes.

File: plugin/src/sbt-test/generator/e2e/src/test/scala/twitch/twirp/example/haberdasher/HaberdasherSpec.scala [hunk 4]
```diff
@@ -78,7 +78,7 @@ class HaberdasherSpec extends Specification {
...
```
[the remark this answers is not in the document]
Comment (rbscgh) [reply plugin/src/sbt-test/generator/e2e/src/test/scala/twitch/twirp/example/haberdasher/HaberdasherSpec.scala]: 🤖 *Automated response from Claude Code* — Addressed in abdba67. Replaced the refutable `@unchecked` binding with `must throwA[TwinagleException].like { case ex: TwinagleException => ... }` (explicit pattern type so `ex.code` resolves). Verified passing on both the sbt 1.x and sbt 2.x scripted axes.

File: build.sbt [hunk 5]
```diff
@@ -57,8 +70,16 @@ lazy val runtime = (project in file("runtime")).settings(
...
+      "com.thesamet.scalapb" %% "scalapb-runtime" % "1.0.0-alpha.5",
+      // scalapb-json4s has only published 1.0.0-alpha.1, which pulls scalapb-runtime alpha.1.
+      // Exclude its transitive scalapb-runtime so only our alpha.5 above remains: sbt's
+      // early-semver check otherwise flags the alpha.1 -> alpha.5 eviction as a hard conflict,
+      // and a per-dependency exclude (unlike dependencyOverrides) serializes into the published
+      // POM/ivy so downstream consumers inherit the coherent single version.
+      ("com.thesamet.scalapb" %% "scalapb-json4s" % "1.0.0-alpha.1")
+        .exclude("com.thesamet.scalapb", "scalapb-runtime_2.12")
+        .exclude("com.thesamet.scalapb", "scalapb-runtime_2.13")
+        .exclude("com.thesamet.scalapb", "scalapb-runtime_3"),
```
Comment (rbscgh) [inline build.sbt:87]: this is probably unacceptable but hopefully will be fixed once 1.0 scalapb is released

File: build.sbt [hunk 6]
```diff
@@ -2,32 +2,30 @@ import sbt.CrossVersion
 
 lazy val scala212  = "2.12.20"
 lazy val scala213  = "2.13.17"
-lazy val scala3LTS = "3.3.7"
+lazy val scala3LTS = "3.3.7" // runtime stays on LTS — it is the end-user library
+lazy val scala3    = "3.8.4" // codegen + plugin Scala-3 axis (matches sbt 2.0.0 DSL)
```
[the remark this answers is not in the document]
Comment (rbscgh) [reply build.sbt:6]: 🤖 *Automated response from Claude Code* — This is a false positive: Scala 3.8.4 does exist on Maven Central and is the version sbt 2.0.0 itself is built with. CI (JDK 17) resolves it and the full `+test +publishLocal +plugin/scripted` passes on the Scala 3 axis, including the sbt 2.0.0 scripted run. No change made.

File: build.sbt (hunk 5 above)
[the remark this answers is not in the document]
Comment (rbscgh) [reply build.sbt:87]: 🤖 *Automated response from Claude Code* — Tried this, but reverted in 76ee32f. `CrossVersion.binary` serializes to the suffix-less artifact id `scalapb-runtime` in the published POM, which does not match `scalapb-runtime_2.13` during a downstream consumer's resolution — the scripted e2e (which resolves the *published* plugin) reproduces the version conflict with it. The explicit _2.12/_2.13/_3 suffixes are required for the exclusion to match in consumer builds; added a comment explaining this.

File: plugin/src/main/scala/com/soundcloud/twinagle/plugin/Twinagle.scala [hunk 7]
```diff
@@ -42,9 +45,14 @@ object Twinagle extends AutoPlugin {
...
+      // Explicit InclExclRule element type: sbt 2 / Scala 3 no longer applies the implicit
+      // OrganizationArtifactName -> InclExclRule conversion that sbt 1 relied on here.
       CrossVersion.partialVersion(scalaVersion.value) match {
-        case Some((3, _)) => Seq("org.scala-lang.modules" % "scala-collection-compat_2.13")
-        case _            => Seq.empty
+        case Some((3, _)) =>
+          Seq[sbt.librarymanagement.InclExclRule](
+            "org.scala-lang.modules" % "scala-collection-compat_2.13"
+          )
+        case _ => Seq.empty[sbt.librarymanagement.InclExclRule]
```
[the remark this answers is not in the document]
Comment (rbscgh) [reply plugin/src/main/scala/com/soundcloud/twinagle/plugin/Twinagle.scala]: 🤖 *Automated response from Claude Code* — Addressed in 76ee32f. Switched to `ExclusionRule("org.scala-lang.modules", "scala-collection-compat_2.13")`, dropping the verbose explicit `InclExclRule` type ascription.
